apiVersion: v1
imagePullSecrets:
- name: jenkins-token
kind: ServiceAccount
metadata:
  creationTimestamp: "2025-02-01T16:39:55Z"
  name: jenkins
  namespace: default
  resourceVersion: "54502"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
