apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-ngnix-app-service
  name: my-ngnix-app-service
spec:
  ports:
  - name: my-ngnix-app-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-app
  type: NodePort
status:
  loadBalancer: {}